#!/bin/bash
# ============================================================================
# PPPoE test rig — a local ISP concentrator, for boxes without a PPPoE line
# ============================================================================
# PPPoE cannot be tested remotely: its frames are Ethernet-level (0x8863 /
# 0x8864) and do not route, so the concentrator has to sit on the same L2
# segment. This builds one out of a veth pair — no cables, no second machine,
# no provider.
#
#     [ PiTun WAN ]  pitun-wan <---veth---> pitun-isp  [ netns pppoe-isp ]
#                                                       pppoe-server
#
# The server lives in a network namespace so its pppd creates its ppp
# interface there. Both ends in one namespace would leave two ppp links on the
# host, which is precisely the case `live_pppoe_interface()` refuses to guess
# between — correct behaviour, but it muddies the test.
#
# WHY THIS IS SAFE TO RUN ON A LIVE BOX: the WAN becomes the veth, not the
# real port. Every firewall drop is scoped to `iifname <wan>`, so the physical
# LAN — the panel, SSH — is untouched no matter how the tunnel behaves.
#
# WHAT IT COSTS: while the session is up, the default route moves to ppp0 and
# points at a concentrator with no internet behind it. The box loses outbound
# connectivity until `down`. Panel and SSH are LAN-local and keep working.
#
# Usage:
#   sudo bash pppoe-test-rig.sh up      # build it, start the server
#   sudo bash pppoe-test-rig.sh status  # what exists right now
#   sudo bash pppoe-test-rig.sh down    # remove every trace
#
# Then in PiTun: WAN port = pitun-wan, mode = PPPoE, user/pass as below.
# ============================================================================
set -uo pipefail

NS="pppoe-isp"
CLIENT_IF="pitun-wan"      # stays on the host — this is PiTun's WAN port
SERVER_IF="pitun-isp"      # moved into the namespace
SERVER_IP="10.222.0.1"
POOL_START="10.222.0.100"
POOL_COUNT=5
USERNAME="pitun-test"
PASSWORD="pitun-test-pppoe"
OPTS="/etc/ppp/pppoe-server-options.pitun-rig"
SECRETS="/etc/ppp/pap-secrets"
SECRET_MARK="# pitun-test-rig"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
err()  { echo -e "${RED}[x]${NC} $*"; }

[[ $EUID -ne 0 ]] && { err "Run as root"; exit 1; }

up() {
    if ! command -v pppoe-server >/dev/null 2>&1; then
        log "Installing pppoe…"
        apt-get install -y -qq pppoe >/dev/null 2>&1 \
            || { err "Could not install the 'pppoe' package"; exit 1; }
    fi

    # Idempotent: a half-built rig from an interrupted run must not wedge this.
    down >/dev/null 2>&1

    log "Creating the veth pair and the namespace…"
    ip netns add "$NS" || { err "Could not create namespace $NS"; exit 1; }
    ip link add "$CLIENT_IF" type veth peer name "$SERVER_IF" \
        || { err "Could not create the veth pair"; down; exit 1; }
    ip link set "$SERVER_IF" netns "$NS"
    ip link set "$CLIENT_IF" up
    ip netns exec "$NS" ip link set lo up
    ip netns exec "$NS" ip link set "$SERVER_IF" up

    # NetworkManager will not offer an interface it has decided not to manage,
    # and PiTun drives the uplink through nmcli.
    if command -v nmcli >/dev/null 2>&1; then
        nmcli device set "$CLIENT_IF" managed yes >/dev/null 2>&1 || true
    fi

    log "Writing the server's pppd options…"
    cat > "$OPTS" <<EOF
# Generated by pppoe-test-rig.sh
require-pap
# NOT `login`: that makes pppd authenticate against the system user database
# through PAM, so a name that exists only in pap-secrets is rejected with
# "user unknown" — the credentials are checked in the wrong place entirely.
lcp-echo-interval 10
lcp-echo-failure 3
ms-dns 1.1.1.1
netmask 255.255.255.0
noipx
EOF

    # One entry serves both ends: the server checks the client against it, and
    # the wildcard server field means it matches whatever name pppd presents.
    if ! grep -q "$SECRET_MARK" "$SECRETS" 2>/dev/null; then
        log "Adding the test credentials to pap-secrets…"
        printf '%s\n"%s" * "%s" *\n' "$SECRET_MARK" "$USERNAME" "$PASSWORD" >> "$SECRETS"
    fi

    log "Starting pppoe-server in the namespace…"
    ip netns exec "$NS" pppoe-server \
        -I "$SERVER_IF" -L "$SERVER_IP" -R "$POOL_START" -N "$POOL_COUNT" \
        -O "$OPTS" \
        || { err "pppoe-server failed to start"; down; exit 1; }

    sleep 1
    if ! ip netns exec "$NS" pgrep -x pppoe-server >/dev/null 2>&1; then
        err "pppoe-server is not running — check 'journalctl -t pppd'"
        down
        exit 1
    fi

    echo ""
    log "Rig is up."
    echo "  WAN port for PiTun : $CLIENT_IF"
    echo "  Mode               : PPPoE"
    echo "  Username           : $USERNAME"
    echo "  Password           : $PASSWORD"
    echo "  Concentrator       : $SERVER_IP, pool from $POOL_START"
    echo ""
    warn "While a session is up the default route points at a concentrator"
    warn "with no internet behind it. Run 'down' when finished."
}

status() {
    echo "namespace:"
    ip netns list 2>/dev/null | grep -q "^$NS" && echo "  $NS present" || echo "  absent"
    echo "veth:"
    ip link show "$CLIENT_IF" >/dev/null 2>&1 \
        && ip -br link show "$CLIENT_IF" | sed 's/^/  /' || echo "  absent"
    echo "server:"
    ip netns exec "$NS" pgrep -ax pppoe-server 2>/dev/null | sed 's/^/  /' || echo "  not running"
    echo "ppp links on the host:"
    ip -br link show type ppp 2>/dev/null | sed 's/^/  /' || echo "  none"
    echo "default route:"
    ip route show default | sed 's/^/  /'
}

down() {
    log "Removing the rig…"
    ip netns exec "$NS" pkill -x pppoe-server 2>/dev/null || true
    # The client-side session belongs to NetworkManager; PiTun's own teardown
    # removes it, but a rig torn down mid-test should not leave one dialling.
    if command -v nmcli >/dev/null 2>&1; then
        nmcli connection delete pitun-wan >/dev/null 2>&1 || true
    fi
    ip netns del "$NS" 2>/dev/null || true
    ip link del "$CLIENT_IF" 2>/dev/null || true
    rm -f "$OPTS"
    if [ -f "$SECRETS" ] && grep -q "$SECRET_MARK" "$SECRETS" 2>/dev/null; then
        sed -i "/$SECRET_MARK/,+1d" "$SECRETS"
    fi
    log "Removed."
}

case "${1:-}" in
    up)     up ;;
    down)   down ;;
    status) status ;;
    *)      echo "Usage: $0 {up|status|down}"; exit 1 ;;
esac
