"""DHCP server for router mode (dnsmasq sidecar).

Only runs when `operating_mode = router`. In gateway mode the upstream router
hands out addresses and none of this is active.

Two things worth knowing about the shape of this:

* **`port=0` is mandatory, not a preference.** dnsmasq is a DNS server as well
  as a DHCP server, and xray already owns `:53` with our per-domain rules, DoH
  upstreams, FakeDNS and the query log. Letting dnsmasq bind DNS would either
  fail to start or quietly take that away. It serves DHCP only.
* **PiTun advertises itself as the resolver.** The whole point of owning the
  LAN is that clients get our DNS — that's what makes routing rules and the
  query log work for devices that never opted in to anything.

Config generation is separated from the container lifecycle so the interesting
part (what we tell clients) is testable without Docker.
"""
from __future__ import annotations

import ipaddress
import logging
from dataclasses import dataclass
from typing import List, Optional, Sequence

logger = logging.getLogger(__name__)

CONF_PATH = "/etc/pitun/dnsmasq.conf"
CONTAINER_NAME = "pitun-dnsmasq"


class DhcpConfigError(ValueError):
    """Raised when the requested DHCP settings could not serve a LAN."""


@dataclass
class StaticLease:
    mac: str
    ip: str
    name: str = ""


@dataclass
class DhcpConfig:
    interface: str          # LAN-facing port dnsmasq binds to
    lan_cidr: str           # e.g. "192.168.10.0/24"
    lan_address: str        # the box's own address on that LAN — gateway + DNS
    pool_start: str
    pool_end: str
    lease_hours: int = 12
    domain: str = ""
    static_leases: Sequence[StaticLease] = ()


def _validate(cfg: DhcpConfig) -> ipaddress.IPv4Network:
    try:
        net = ipaddress.ip_network(cfg.lan_cidr, strict=False)
    except ValueError as exc:
        raise DhcpConfigError(f"lan_cidr {cfg.lan_cidr!r} is not a valid subnet: {exc}")
    if not isinstance(net, ipaddress.IPv4Network):
        raise DhcpConfigError("Only IPv4 LANs are supported")

    def _addr(value: str, label: str) -> ipaddress.IPv4Address:
        try:
            ip = ipaddress.ip_address(value)
        except ValueError as exc:
            raise DhcpConfigError(f"{label} {value!r} is not a valid IPv4 address: {exc}")
        if ip not in net:
            raise DhcpConfigError(f"{label} {value} is outside the LAN subnet {net}")
        return ip  # type: ignore[return-value]

    start = _addr(cfg.pool_start, "Pool start")
    end = _addr(cfg.pool_end, "Pool end")
    gw = _addr(cfg.lan_address, "LAN address")

    if start > end:
        raise DhcpConfigError(
            f"Pool start {start} is above pool end {end} — the range is empty"
        )
    # The classic footgun: hand out the router's own address to a client and
    # the LAN starts fighting itself. dnsmasq will not catch this for us.
    if start <= gw <= end:
        raise DhcpConfigError(
            f"The box's own LAN address {gw} falls inside the DHCP pool "
            f"{start}-{end}. Move the pool (or the address) so they don't "
            f"overlap, otherwise a client can be handed the gateway's address."
        )
    if cfg.lease_hours < 1:
        raise DhcpConfigError("Lease time must be at least 1 hour")
    return net


def render_dnsmasq_conf(cfg: DhcpConfig) -> str:
    """Produce the dnsmasq config, or raise DhcpConfigError."""
    net = _validate(cfg)

    lines = [
        "# Generated by PiTun — do not edit; changes are overwritten.",
        "",
        "# DHCP only. xray owns :53 with PiTun's DNS rules and query log,",
        "# so dnsmasq's own resolver is switched off entirely.",
        "port=0",
        "",
        f"interface={cfg.interface}",
        # Never answer on anything but the LAN port — a DHCP server replying
        # on the WAN side is both useless and hostile to the ISP's network.
        "bind-interfaces",
        "except-interface=lo",
        "no-resolv",
        "",
        f"dhcp-range={cfg.pool_start},{cfg.pool_end},{net.netmask},{cfg.lease_hours}h",
        # option 3 (router) and option 6 (DNS) both point at us.
        f"dhcp-option=3,{cfg.lan_address}",
        f"dhcp-option=6,{cfg.lan_address}",
        "dhcp-authoritative",
        "log-dhcp",
    ]
    if cfg.domain:
        lines += [f"domain={cfg.domain}", f"dhcp-option=15,{cfg.domain}"]

    if cfg.static_leases:
        lines += ["", "# Reserved addresses"]
        for lease in cfg.static_leases:
            try:
                ip = ipaddress.ip_address(lease.ip)
            except ValueError:
                logger.warning("DHCP: skipping reservation with bad IP %r", lease.ip)
                continue
            if ip not in net:
                logger.warning(
                    "DHCP: skipping reservation %s -> %s (outside %s)",
                    lease.mac, lease.ip, net,
                )
                continue
            suffix = f",{lease.name}" if lease.name else ""
            lines.append(f"dhcp-host={lease.mac},{lease.ip}{suffix}")

    return "\n".join(lines) + "\n"


def default_pool_for(lan_cidr: str, lan_address: str) -> tuple[str, str]:
    """Suggest a pool that doesn't collide with the box's own address.

    Uses the upper half of the subnet, which keeps the low addresses free for
    the gateway and any statically-configured infrastructure — the convention
    most home networks already follow.
    """
    net = ipaddress.ip_network(lan_cidr, strict=False)
    hosts = list(net.hosts())
    if len(hosts) < 4:
        raise DhcpConfigError(f"Subnet {lan_cidr} is too small to serve DHCP")
    half = len(hosts) // 2
    start, end = hosts[half], hosts[-1]
    gw = ipaddress.ip_address(lan_address)
    if start <= gw <= end:
        # Gateway sits in the upper half — use the lower half instead.
        start, end = hosts[1], hosts[half - 1]
    return str(start), str(end)


# ── Container lifecycle ──────────────────────────────────────────────────────
#
# Same shape as the naive sidecar: host networking (DHCP is broadcast traffic
# on a specific link, it cannot work from a bridge namespace), restart policy,
# and the config bind-mounted so a settings change is a file write plus a
# restart rather than an image rebuild.

import asyncio  # noqa: E402  (kept next to the code that uses it)
import os  # noqa: E402

from app.config import settings  # noqa: E402

_HOST_CONF_DIR = "/etc/pitun"


def _docker_client():
    import docker
    return docker.DockerClient(base_url=os.environ.get("DOCKER_HOST", settings.docker_host))


def write_conf(conf: str) -> str:
    """Write the rendered config where the container will read it."""
    os.makedirs(_HOST_CONF_DIR, exist_ok=True)
    path = os.path.join(_HOST_CONF_DIR, "dnsmasq.conf")
    with open(path, "w") as f:
        f.write(conf)
    return path


def _start_sync(cfg: DhcpConfig) -> dict:
    import docker
    from docker.errors import ImageNotFound, NotFound

    conf = render_dnsmasq_conf(cfg)   # raises DhcpConfigError before anything runs
    write_conf(conf)

    client = _docker_client()
    try:
        existing = client.containers.get(CONTAINER_NAME)
        existing.remove(force=True)
    except NotFound:
        pass

    try:
        client.containers.run(
            image=settings.dnsmasq_image,
            name=CONTAINER_NAME,
            detach=True,
            network_mode="host",
            restart_policy={"Name": "unless-stopped"},
            # NET_ADMIN for the raw socket dnsmasq uses to answer DHCP before
            # the client has an address; NET_BIND_SERVICE for the :67 bind.
            cap_add=["NET_ADMIN", "NET_RAW", "NET_BIND_SERVICE"],
            volumes={_HOST_CONF_DIR: {"bind": "/etc/dnsmasq", "mode": "ro"}},
        )
    except ImageNotFound:
        raise DhcpConfigError(
            f"Image {settings.dnsmasq_image} not found — build it first: "
            f"docker build -t {settings.dnsmasq_image} docker/dnsmasq/"
        )
    logger.info("DHCP server started on %s (%s-%s)",
                cfg.interface, cfg.pool_start, cfg.pool_end)
    return {"running": True, "interface": cfg.interface}


def _stop_sync() -> dict:
    from docker.errors import NotFound
    try:
        c = _docker_client().containers.get(CONTAINER_NAME)
        c.remove(force=True)
        logger.info("DHCP server stopped")
        return {"running": False}
    except NotFound:
        return {"running": False}


def _status_sync() -> dict:
    from docker.errors import NotFound
    try:
        c = _docker_client().containers.get(CONTAINER_NAME)
        c.reload()
        return {"exists": True, "running": c.status == "running", "status": c.status}
    except NotFound:
        return {"exists": False, "running": False, "status": "absent"}
    except Exception as exc:  # noqa: BLE001 — status must never raise at the caller
        return {"exists": False, "running": False, "status": f"error: {exc}"}


async def start(cfg: DhcpConfig) -> dict:
    return await asyncio.to_thread(_start_sync, cfg)


async def stop() -> dict:
    return await asyncio.to_thread(_stop_sync)


async def status() -> dict:
    return await asyncio.to_thread(_status_sync)
