"""Two-hop proxy chain orchestrator (since v1.3.0-beta.7).

Wires together an EU **exit** x-ui panel and a RU **relay** x-ui panel
to recreate the working setup-eu.sh + setup-relay.sh pattern from the
user's reference scripts. The orchestrator is the single code path
that knows how to:

  1. Create N exit-side inbounds (xhttp + Reality, masked under
     exit_sni) on the EU panel — one per channel.
  2. Create N relay-side inbounds (TCP + Reality, masked under
     channel.client_sni) on the RU panel.
  3. Stitch them together with an `xrayTemplateConfig` push to the
     relay panel: outbounds[chain-<channel>] mirror each exit-inbound,
     routing.rules pair `inboundTag=<relay-tag>` → `outboundTag=
     chain-<channel>`. After the push we restart Xray on the relay
     so the new template takes effect.

The orchestrator is **atomic-ish**: if step N fails, we delete every
inbound we created in steps 1..N-1 via the panel API before raising.
Real atomicity across two independent panels isn't achievable (the
exit-side creates land before the relay-side ones, and either panel
can flake mid-way), but rollback turns a partial failure into a
clean re-runnable state instead of stranded zombie inbounds.

Schema decisions documented inline:
  * Inbound `tag` is set explicitly to `chain-<chain_id>-<name>-{exit|
    relay}`. The panel doesn't auto-tag inbounds, and xray needs an
    exact-match tag for the routing rules. Setting it here keeps
    /sync (Phase 6 part 2) cheap — we can find our inbounds by tag
    without trusting the remote_id alone.
  * Reality keys are generated by the panel's `getNewX25519Cert`
    endpoint (per-side, per-channel). We pull both halves of each
    pair into the DB so re-pushing the xrayTemplateConfig after a
    panel restart doesn't need to round-trip the panel for them.
  * `xrayTemplateConfig` is the panel's own setting key for "config
    Xray uses on start". We POST it via `/panel/setting/update` — the
    same path 3x-ui's web UI uses for its `Xray Config` editor.
"""
from __future__ import annotations

import json
import logging
import secrets
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from sqlmodel.ext.asyncio.session import AsyncSession

from app.core.ssh import exec_remote_script
from app.core.xui_api import XuiAPIError, XuiClient
from app.models import (
    ChainChannel,
    ChainClient,
    ChainClientChannel,
    ProxyChain,
    Server,
    XuiServer,
)

logger = logging.getLogger(__name__)


def _no_expire_on_commit(session: AsyncSession) -> None:
    """Disable expire-on-commit for the rest of this session's life.

    SQLAlchemy's default is to mark every attached instance as expired
    after `commit()`, so the next attribute access reloads via the DB.
    In a sync session that's transparent; in an AsyncSession the
    reload tries to dispatch IO through the sync greenlet and
    crashes with `MissingGreenlet: can't call await_only() here`.

    Every orchestrate_* function below commits multiple times and
    keeps reading from the same ORM instances afterwards
    (`exit_xs.api_token`, `exit_srv.host`, `channel.exit_port`, …).
    Snapshotting each field by hand turned out to be brittle — new
    fields kept getting added and the bug re-surfaced — so we just
    flip the session-level flag once at entry and read freely.

    Safe because the orchestrators are the sole writer to the
    XuiServer / Server / ChainChannel rows they touch during the
    call; nothing else races to overwrite them mid-flight.
    """
    try:
        session.sync_session.expire_on_commit = False
    except Exception:  # noqa: BLE001 — be defensive; SA internals may rename
        pass


async def _ufw_chain_ports(
    server: Server, ports: List[int], *, action: str,
) -> None:
    """Open / close TCP ports on the VPS via SSH + UFW.

    UFW on a default-deny VPS will silently drop SYNs to chain inbound
    ports until we explicitly allow them. The reference setup-eu.sh /
    setup-relay.sh do this inline because they run on the VPS itself;
    PiTun creates inbounds through the panel API, so the UFW step has
    to happen separately.

    `action` is "allow" or "delete-allow"; best-effort — a failure
    here is logged but doesn't abort the chain operation. The user
    can always open / close the port manually.
    """
    if not ports:
        return
    cmd = "set -e\n"
    for p in ports:
        if action == "allow":
            cmd += f"ufw allow {int(p)}/tcp || true\n"
        elif action == "delete-allow":
            cmd += f"ufw delete allow {int(p)}/tcp || true\n"
    cmd += "ufw reload || true\n"
    try:
        res = await exec_remote_script(
            host=server.host, port=server.port or 22,
            username=server.user or "root",
            password=server.password,
            private_key=server.private_key,
            script_content=cmd,
            timeout=30.0,
        )
        if not res.ok:
            logger.warning(
                "ufw %s on %s ports=%s: exit=%s err=%s",
                action, server.host, ports, res.exit_code, res.error,
            )
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "ufw %s on %s ports=%s raised: %s",
            action, server.host, ports, exc,
        )


async def _clear_xray_template_via_ssh(server: Server) -> None:
    """Hard-clear `xrayTemplateConfig` on the panel + restart x-ui.

    Why over SSH instead of the panel API:
      The `/panel/xray/update` endpoint only knows how to set
      `xraySetting` to a value. Pushing an empty string stores `''`
      in the settings table but the panel keeps using the previously
      assembled `bin/config.json` — so the chain outbound + routing
      rule survive a subsequent restart and any unmatched inbound
      traffic ends up falling through to `* -> blocked`. Only a hard
      `DELETE FROM settings WHERE key = 'xrayTemplateConfig'` + an
      explicit `x-ui restart` causes the panel to rebuild routing
      from defaults (api → api, geoip:private → blocked,
      bittorrent → blocked) so standalone inbounds get the implicit
      catch-all `direct` outbound xray picks when no rule matches.

    Called on the LAST chain-delete for a relay panel so the operator
    can keep adding plain inbounds without their traffic blackholing.
    Best-effort: failure is logged but doesn't unwind the delete.
    """
    cmd = (
        "set -e\n"
        # The panel can install its sqlite in either location depending
        # on how old the installer was; try both.
        "for db in /etc/x-ui/x-ui.db /usr/local/x-ui/db/x-ui.db; do\n"
        "  if [ -f \"$db\" ]; then\n"
        "    sqlite3 \"$db\" \"DELETE FROM settings WHERE key='xrayTemplateConfig';\"\n"
        "  fi\n"
        "done\n"
        "x-ui restart >/dev/null 2>&1 || systemctl restart x-ui >/dev/null 2>&1 || true\n"
    )
    try:
        # `x-ui restart` can take 30-45s on slow VPSes (Go's runtime
        # init + xray's startup + the panel writing a fresh
        # bin/config.json from sqlite). Give it real headroom; the
        # operator-visible side of the chain delete already returned
        # by the time this runs, so a long wait here doesn't block UX.
        res = await exec_remote_script(
            host=server.host, port=server.port or 22,
            username=server.user or "root",
            password=server.password,
            private_key=server.private_key,
            script_content=cmd,
            timeout=90.0,
        )
        if not res.ok:
            logger.warning(
                "clear xrayTemplateConfig on %s: exit=%s err=%s",
                server.host, res.exit_code, res.error,
            )
        else:
            logger.info(
                "Last chain removed from relay %s — xrayTemplateConfig "
                "deleted + x-ui restarted (panel auto-routing restored).",
                server.host,
            )
    except Exception as exc:  # noqa: BLE001
        logger.warning(
            "clear xrayTemplateConfig on %s raised: %s", server.host, exc,
        )


# ── Input shapes (used by the API layer + tests) ────────────────────────────


@dataclass
class ChannelDraft:
    """User-supplied channel parameters for a chain create request.

    Everything except `name` has a defaulted-or-generated path:
      * `exit_port` / `relay_port` — if 0/empty, the orchestrator
        picks free random ports in well-separated ranges (10000-19999
        for exit, 20000-29999 for relay) so collisions across channels
        within the same chain are vanishingly rare. The orchestrator
        also probes the panel's existing inbound list for the chosen
        port and re-rolls on conflict.
      * `exit_xhttp_path` — defaults to `/api/v1/<name>`.
      * `client_sni` — must be supplied by the user; this is the
        whole point of having multiple channels (different SNI =
        different DPI cover).
      * `relay_inbound_remark` / `exit_inbound_remark` — defaults
        derived from `name`.
    """

    name: str               # alnum + `-` + `_`, max 64 chars
    client_sni: str         # the SNI DPI sees on client→relay
    exit_port: int = 0      # 0 = auto-pick
    relay_port: int = 0     # 0 = auto-pick
    exit_xhttp_path: str = ""  # empty = `/api/v1/<name>`
    relay_remark: str = ""  # empty = `VPN-<name.upper()>`
    exit_remark: str = ""   # empty = `<name.upper()>-Exit`


@dataclass
class ChainCreateDraft:
    """Top-level chain create request — what the API layer passes
    into `orchestrate_create`."""

    name: str
    exit_xui_server_id: int
    relay_xui_server_id: int
    exit_sni: str
    channels: List[ChannelDraft]


# ── Tag conventions ─────────────────────────────────────────────────────────


def _exit_tag(chain_id: int, channel_name: str) -> str:
    """The xray inbound `tag` for an exit-side inbound.

    Format `chain-<id>-<name>-exit`. Used both as the inbound's own
    tag (so /sync can find it again after a panel reboot) and as
    the relay outbound's name (so the routing rule on the relay
    references it cleanly)."""
    return f"chain-{chain_id}-{channel_name}-exit"


def _relay_tag(chain_id: int, channel_name: str) -> str:
    return f"chain-{chain_id}-{channel_name}-relay"


# ── Build helpers — keep panel-payload generation pure-functional so ───────
# the orchestrator can be unit-tested without an httpx pool.


def _sniff() -> Dict[str, Any]:
    """Standard sniffing block for both sides. Copy from xui_presets's
    helper but inlined here so the chain layer doesn't depend on the
    preset module (presets are user-facing single-server inbounds —
    chains build their own wire shapes)."""
    return {
        "enabled": True,
        "destOverride": ["http", "tls", "quic", "fakedns"],
        "metadataOnly": False,
        "routeOnly": False,
    }


def _build_exit_inbound_payload(
    *,
    chain_id: int,
    channel: ChannelDraft,
    bootstrap_uuid: str,
    exit_sni: str,
    private_key: str,
    public_key: str,
    short_id: str,
    bootstrap_email: str,
) -> Dict[str, Any]:
    """xhttp + Reality inbound on the exit panel.

    The `clients` array carries ONE bootstrap UUID — the relay's
    outbound will use this to dial in. ChainClient creation later
    appends more clients to this same inbound via addClient, but
    those are for the relay→exit hop on a per-user basis. Wait, no:
    in the user's reference setup-relay.sh the relay-side outbound
    has ONE bootstrap UUID baked into the xrayTemplateConfig, and
    that UUID is shared across all relay-side clients (the routing
    layer doesn't care which user it is — the per-user identity
    is on the client→relay hop). So we ship one bootstrap UUID and
    leave it at that.
    """
    settings = {
        "clients": [
            {
                "id": bootstrap_uuid,
                "flow": "",
                "email": bootstrap_email,
                "limitIp": 0, "totalGB": 0, "expiryTime": 0,
                "enable": True, "tgId": "", "subId": "",
            },
        ],
        "decryption": "none",
        "fallbacks": [],
    }
    stream = {
        "network": "xhttp",
        "security": "reality",
        "realitySettings": {
            "show": False, "xver": 0,
            "dest": f"{exit_sni}:443",
            "serverNames": [exit_sni],
            "privateKey": private_key,
            "minClient": "", "maxClient": "", "maxTimediff": 0,
            "shortIds": [short_id],
            "settings": {
                "publicKey": public_key,
                "fingerprint": "chrome",
                "serverName": "",
                "spiderX": "/",
            },
        },
        "xhttpSettings": {
            "path": channel.exit_xhttp_path or f"/api/v1/{channel.name}",
            "mode": "packet-up",
        },
    }
    return {
        "up": 0, "down": 0, "total": 0,
        "remark": channel.exit_remark or f"{channel.name.upper()}-Exit",
        "enable": True, "expiryTime": 0,
        "listen": "", "port": channel.exit_port,
        "protocol": "vless",
        "tag": _exit_tag(chain_id, channel.name),
        "settings": settings,
        "streamSettings": stream,
        "sniffing": _sniff(),
    }


def _build_relay_inbound_payload(
    *,
    chain_id: int,
    channel: ChannelDraft,
    bootstrap_uuid: str,
    private_key: str,
    public_key: str,
    short_id: str,
    bootstrap_email: str,
) -> Dict[str, Any]:
    """TCP + Reality + xtls-rprx-vision inbound on the relay panel.

    This is what end-user clients dial. `client_sni` is the
    masquerade host the DPI between the user and the relay sees —
    a domain the operator picked for their threat model. PiTun
    ships no defaults here; the channel-create UI is a free-text
    field.
    """
    sni = channel.client_sni
    settings = {
        "clients": [
            {
                "id": bootstrap_uuid,
                "flow": "xtls-rprx-vision",
                "email": bootstrap_email,
                "limitIp": 0, "totalGB": 0, "expiryTime": 0,
                "enable": True, "tgId": "", "subId": "",
            },
        ],
        "decryption": "none",
        "fallbacks": [],
    }
    stream = {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
            "show": False, "xver": 0,
            "dest": f"{sni}:443",
            "serverNames": [sni],
            "privateKey": private_key,
            "minClient": "", "maxClient": "", "maxTimediff": 0,
            "shortIds": [short_id],
            "settings": {
                "publicKey": public_key,
                "fingerprint": "chrome",
                "serverName": "",
                "spiderX": "/",
            },
        },
        "tcpSettings": {
            "acceptProxyProtocol": False,
            "header": {"type": "none"},
        },
    }
    return {
        "up": 0, "down": 0, "total": 0,
        "remark": channel.relay_remark or f"VPN-{channel.name.upper()}",
        "enable": True, "expiryTime": 0,
        "listen": "", "port": channel.relay_port,
        "protocol": "vless",
        "tag": _relay_tag(chain_id, channel.name),
        "settings": settings,
        "streamSettings": stream,
        "sniffing": _sniff(),
    }


def build_xray_template_config(
    *,
    chain: ProxyChain,
    channels: List[ChainChannel],
    exit_host: str,
) -> Dict[str, Any]:
    """Assemble the relay-side `xrayTemplateConfig`.

    Layout (matches setup-relay.sh):
      * `api` block + dokodemo-door inbound on a random localhost port
        (the panel's own stats/api channel).
      * One `chain-<name>` outbound per channel — each is a vless+
        xhttp+reality client config pointing at the exit panel's
        matching inbound (same UUID, public_key, shortId we just
        created in step 1 of orchestrate_create).
      * `direct` + `blocked` outbounds as a baseline (any rule that
        doesn't hit a chain outbound falls through to `direct`).
      * Routing rules:
          - inboundTag=["api"]            → outboundTag=api
          - inboundTag=[<relay-tag>]      → outboundTag=chain-<name>
          - blocked rule for bittorrent (matches reference script).
    """
    # The panel will replace `${API_PORT}` with its own random port at
    # apply time; we pick one here deterministically so re-pushes
    # don't churn it. Stays in the well-known free range above 50000.
    api_port = 50000 + (chain.id or 0) % 9999

    outbounds: List[Dict[str, Any]] = [
        {"tag": "api", "protocol": "freedom", "settings": {}},
    ]
    routing_rules: List[Dict[str, Any]] = [
        {"type": "field", "inboundTag": ["api"], "outboundTag": "api"},
    ]

    for ch in channels:
        # Chain id in the tag so two chains sharing the same channel
        # name on the same relay don't collide when we rebuild the
        # combined template (Phase 9 bug — pushed an empty template
        # on delete that wiped routes for OTHER chains on the relay).
        chain_tag = f"chain-{chain.id or 0}-{ch.name}"
        outbounds.append({
            "tag": chain_tag,
            "protocol": "vless",
            "settings": {
                "vnext": [
                    {
                        "address": exit_host,
                        "port": ch.exit_port,
                        "users": [
                            {
                                "id": ch.exit_uuid,
                                "flow": "",
                                "encryption": "none",
                            },
                        ],
                    },
                ],
            },
            "streamSettings": {
                "network": "xhttp",
                "security": "reality",
                "realitySettings": {
                    "fingerprint": "chrome",
                    "serverName": chain.exit_sni,
                    "publicKey": ch.exit_pbk,
                    "shortId": ch.exit_sid,
                },
                "xhttpSettings": {
                    "mode": "packet-up",
                    "path": ch.exit_xhttp_path,
                },
            },
        })
        routing_rules.append({
            "type": "field",
            "inboundTag": [_relay_tag(chain.id or 0, ch.name)],
            "outboundTag": chain_tag,
        })

    # Tail: direct + blocked baseline + the bittorrent block rule
    # from the reference scripts (matches user expectation that BT
    # never leaks through the chain).
    outbounds.append({
        "tag": "direct", "protocol": "freedom",
        "settings": {"domainStrategy": "AsIs"},
    })
    outbounds.append({
        "tag": "blocked", "protocol": "blackhole", "settings": {},
    })
    routing_rules.append({
        "type": "field", "outboundTag": "blocked",
        "protocol": ["bittorrent"],
    })

    return {
        "log": {"loglevel": "warning"},
        "api": {
            "services": ["HandlerService", "LoggerService", "StatsService"],
            "tag": "api",
        },
        "inbounds": [
            {
                "listen": "127.0.0.1",
                "port": api_port,
                "protocol": "dokodemo-door",
                "settings": {"address": "127.0.0.1"},
                "tag": "api",
            },
        ],
        "outbounds": outbounds,
        "routing": {
            "domainStrategy": "IPIfNonMatch",
            "rules": routing_rules,
        },
        "policy": {
            "levels": {
                "0": {"statsUserDownlink": True, "statsUserUplink": True},
            },
            "system": {
                "statsInboundDownlink": True,
                "statsInboundUplink": True,
            },
        },
        "stats": {},
    }


async def build_combined_relay_template(
    *,
    session: AsyncSession,
    relay_xui_server_id: int,
    exclude_chain_id: Optional[int] = None,
) -> Dict[str, Any]:
    """Build a single xrayTemplateConfig that covers EVERY chain
    currently bound to this relay panel.

    The relay's xrayTemplateConfig is a panel-wide setting — one
    template per panel — so a per-chain push wipes any sibling chain
    that happened to share the same relay. We instead rebuild from
    the DB on every create/delete: pull all chains where
    `relay_xui_server_id == this_panel` (minus `exclude_chain_id`
    when the caller is mid-delete), walk their channels, and merge.

    Outbound tags are namespaced as `chain-<chain_id>-<channel_name>`
    so two different chains on the same relay can have channels
    with identical names without colliding.
    """
    # Sqlmodel select kept local to avoid a circular import.
    from sqlmodel import select as _select

    q = _select(ProxyChain).where(
        ProxyChain.relay_xui_server_id == relay_xui_server_id,
    )
    if exclude_chain_id is not None:
        q = q.where(ProxyChain.id != exclude_chain_id)
    chains_for_panel = list((await session.exec(q)).all())

    # Synthesise a template that aggregates every chain's outbounds /
    # rules. Easiest path: build per-chain and stitch the lists. We
    # use the first chain (sorted by id) as the "owner" for the
    # api-inbound port nonce so re-pushes stay deterministic.
    aggregated_outbounds: List[Dict[str, Any]] = [
        {"tag": "api", "protocol": "freedom", "settings": {}},
    ]
    aggregated_rules: List[Dict[str, Any]] = [
        {"type": "field", "inboundTag": ["api"], "outboundTag": "api"},
    ]

    chains_for_panel.sort(key=lambda c: c.id or 0)
    api_port = 50001
    for ch_idx, c in enumerate(chains_for_panel):
        channels_q = _select(ChainChannel).where(ChainChannel.chain_id == c.id)
        chs = list((await session.exec(channels_q)).all())
        if not chs:
            continue
        # Need exit_host for the per-chain outbound. Each chain can
        # have its own exit panel — resolve via the chain's
        # exit_xui_server_id → Server.host.
        exit_xs_row = await session.get(XuiServer, c.exit_xui_server_id)
        exit_srv_row = (
            await session.get(Server, exit_xs_row.server_id)
            if exit_xs_row else None
        )
        exit_host_val = exit_srv_row.host if exit_srv_row else "127.0.0.1"
        per_chain = build_xray_template_config(
            chain=c, channels=chs, exit_host=exit_host_val,
        )
        # Skip per-chain's api/direct/blocked baseline — we add it
        # once at the bottom. Keep only the `chain-*` outbounds and
        # rules.
        for ob in per_chain.get("outbounds", []):
            tag = ob.get("tag") or ""
            if tag.startswith("chain-"):
                aggregated_outbounds.append(ob)
        for r in per_chain.get("routing", {}).get("rules", []):
            out_tag = r.get("outboundTag") or ""
            if out_tag.startswith("chain-"):
                aggregated_rules.append(r)
        if ch_idx == 0:
            # api_port is derived from the chain id; first chain wins.
            api_port = 50000 + (c.id or 0) % 9999

    # Tail outbounds + the bittorrent block rule. Same as a single-
    # chain template.
    aggregated_outbounds.append({
        "tag": "direct", "protocol": "freedom",
        "settings": {"domainStrategy": "AsIs"},
    })
    aggregated_outbounds.append({
        "tag": "blocked", "protocol": "blackhole", "settings": {},
    })
    aggregated_rules.append({
        "type": "field", "outboundTag": "blocked",
        "protocol": ["bittorrent"],
    })

    return {
        "log": {"loglevel": "warning"},
        "api": {
            "services": ["HandlerService", "LoggerService", "StatsService"],
            "tag": "api",
        },
        "inbounds": [
            {
                "listen": "127.0.0.1", "port": api_port,
                "protocol": "dokodemo-door",
                "settings": {"address": "127.0.0.1"},
                "tag": "api",
            },
        ],
        "outbounds": aggregated_outbounds,
        "routing": {
            "domainStrategy": "IPIfNonMatch",
            "rules": aggregated_rules,
        },
        "policy": {
            "levels": {
                "0": {"statsUserDownlink": True, "statsUserUplink": True},
            },
            "system": {
                "statsInboundDownlink": True, "statsInboundUplink": True,
            },
        },
        "stats": {},
    }


# ── Port allocation ─────────────────────────────────────────────────────────


def _pick_port(
    used_local: set[int],
    used_remote: set[int],
    low: int,
    high: int,
    max_tries: int = 64,
) -> int:
    """Pick a free TCP port in [low, high] avoiding both already-
    chosen channel ports (`used_local`) and the panel's existing
    inbound list (`used_remote`). Bumps `used_local` in place.
    Raises if no port found in `max_tries`."""
    for _ in range(max_tries):
        candidate = secrets.randbelow(high - low + 1) + low
        if candidate in used_local or candidate in used_remote:
            continue
        used_local.add(candidate)
        return candidate
    raise RuntimeError(
        f"Couldn't find a free port in [{low}, {high}] "
        f"after {max_tries} tries; "
        f"local={sorted(used_local)} remote={sorted(used_remote)}",
    )


# ── Main orchestrator ──────────────────────────────────────────────────────


def _api_base_url(xs: XuiServer, srv: Server) -> str:
    """Mirror of the helper in api/xui.py. Duplicated to avoid an
    import cycle (xui_chain → api/xui → models).

    Bare mode → plain HTTP on a random high port (panel uses no cert).
    xui-pro mode → HTTPS via LE cert wired into the panel's
    webCertFile / webCertKey settings by setup-xui-server.sh's
    section 4b.
    """
    if xs.mode == "xui-pro" and xs.domain:
        return f"https://{xs.domain}:{xs.panel_port}{xs.panel_basepath}"
    return f"http://{srv.host}:{xs.panel_port}{xs.panel_basepath}"


def _wrap_settings_json(payload: Dict[str, Any]) -> Dict[str, Any]:
    """3x-ui stores `settings` / `streamSettings` / `sniffing` as
    JSON-in-JSON: the outer body has them as strings, not nested
    objects. Same quirk as add_client (see xui_api.py)."""
    wire = dict(payload)
    for key in ("settings", "streamSettings", "sniffing"):
        if key in wire and not isinstance(wire[key], str):
            wire[key] = json.dumps(wire[key])
    return wire


async def _push_xray_template(
    *,
    relay_client: XuiClient,
    template: Dict[str, Any],
) -> None:
    """Replace the relay's xray template via /panel/xray/update.

    3x-ui v3.0.1 dropped `xrayTemplateConfig` from /panel/setting/all
    — xray config now lives in its own XraySettingController under
    /panel/xray/*. We fetch the current template (just to preserve
    `outboundTestUrl`), then push the new one. Cookie+CSRF auth —
    requires the relay XuiClient to be built with `panel_user` +
    `panel_pass`.
    """
    current = await relay_client.get_xray_setting()
    test_url = current.get("outboundTestUrl") if isinstance(current, dict) else None
    await relay_client.push_xray_setting(template, test_url)


async def _restart_xray(relay_client: XuiClient) -> None:
    """Restart Xray on the relay so it picks up the new template."""
    await relay_client.restart_xray()


async def orchestrate_create(
    *,
    draft: ChainCreateDraft,
    session: AsyncSession,
) -> ProxyChain:
    """Create a chain end-to-end.

    Steps:
      1. Validate the panels exist + load their parent Server rows.
      2. Allocate ports (random, conflict-checked against each panel's
         live inbound list).
      3. Create the ProxyChain row + channel drafts in DB (status=
         pending) — gives us a `chain_id` to use in tags.
      4. For each channel:
         a. getNewUUID + getNewX25519Cert × 2 (one for exit, one for
            relay; shortIds are local random).
         b. POST add_inbound on the exit panel.
         c. POST add_inbound on the relay panel.
         d. Update the ChainChannel row with remote_ids + Reality
            material.
      5. Build the relay xrayTemplateConfig from the now-populated
         channels + push to the relay panel.
      6. Restart Xray on the relay.
      7. Flip chain.status = 'deployed'.

    Rollback: any exception in steps 4-6 triggers `_rollback_inbounds`
    which deletes every panel-side inbound we got a remote_id for,
    then re-raises with a wrapped error message. The DB rows are
    flagged status='failed' so the UI can show the failure + offer
    delete/retry — they're NOT auto-removed because partial state
    on the panels may still need manual cleanup the user wants to
    see.
    """
    _no_expire_on_commit(session)
    # Step 1 — resolve panels.
    exit_xs = await session.get(XuiServer, draft.exit_xui_server_id)
    relay_xs = await session.get(XuiServer, draft.relay_xui_server_id)
    if exit_xs is None or relay_xs is None:
        raise ValueError("exit_xui_server_id or relay_xui_server_id not found")
    if exit_xs.id == relay_xs.id:
        raise ValueError("exit and relay must be different panels")

    exit_srv = await session.get(Server, exit_xs.server_id)
    relay_srv = await session.get(Server, relay_xs.server_id)
    if exit_srv is None or relay_srv is None:
        raise RuntimeError("Server row missing for one of the panels")

    # Channel-name uniqueness check (DB will enforce via the
    # composite unique constraint anyway, but a clean 400 beats a
    # mid-orchestration IntegrityError).
    seen_names: set[str] = set()
    for ch in draft.channels:
        if ch.name in seen_names:
            raise ValueError(f"Duplicate channel name in draft: {ch.name!r}")
        seen_names.add(ch.name)

    exit_url = _api_base_url(exit_xs, exit_srv)
    relay_url = _api_base_url(relay_xs, relay_srv)

    # Snapshot every ORM attribute we'll need AFTER the step-3 commit
    # below. The commit expires every attached instance, and any
    # subsequent attribute read triggers SQLAlchemy's sync lazy-load
    # callback inside the async session — `MissingGreenlet: can't call
    # await_only() here`. Cache them all here once.
    exit_token = exit_xs.api_token
    relay_token = relay_xs.api_token
    exit_host = exit_srv.host
    relay_host = relay_srv.host  # noqa: F841 — kept for symmetry / future use
    # Cookie+CSRF creds — only the relay needs them (to update
    # xrayTemplateConfig via /panel/setting/update in step 5).
    relay_user = relay_xs.panel_user
    relay_pass = relay_xs.panel_pass

    # Step 2 — port allocation.
    # Probe each panel for ports already in use so we don't collide
    # with hand-added inbounds the operator may have set up.
    async with XuiClient(
        base_url=exit_url, api_token=exit_token, verify_tls=False,
    ) as exit_client:
        exit_existing = await exit_client.list_inbounds()
    async with XuiClient(
        base_url=relay_url, api_token=relay_token, verify_tls=False,
    ) as relay_client:
        relay_existing = await relay_client.list_inbounds()

    exit_used = {int(ib.get("port") or 0) for ib in exit_existing}
    relay_used = {int(ib.get("port") or 0) for ib in relay_existing}
    # xui-pro panels run on a domain → Caddy/nginx/LE-ACME hold
    # ports 80 + 443 outside the panel's own inbound list. Binding
    # an inbound there makes Xray start with "address already in
    # use" and leaves the chain half-broken. Reserve them upfront.
    if exit_xs.mode == "xui-pro":
        exit_used |= {80, 443}
    if relay_xs.mode == "xui-pro":
        relay_used |= {80, 443}

    # Per-draft uniqueness pre-check. Two channels claiming the same
    # port on the same panel side will succeed on the API level (the
    # panel happily takes both into its sqlite) but xray will only
    # bind one of them, leaving the other's Reality keys orphan. The
    # client URL for the orphan channel keeps "connecting" on TCP
    # (xray's other inbound is listening) but Reality handshake
    # silently drops because the keys don't match → speedtest shows
    # "too small (0B)". Catch this UP FRONT instead of letting the
    # operator chase a silent-failure mode after the fact.
    user_exit_ports: Dict[int, str] = {}
    user_relay_ports: Dict[int, str] = {}
    for ch in draft.channels:
        if ch.exit_port:
            if ch.exit_port in user_exit_ports:
                raise ValueError(
                    f"Channels {user_exit_ports[ch.exit_port]!r} and {ch.name!r} "
                    f"both claim exit_port {ch.exit_port} — each channel must "
                    "land on a different port on the exit panel."
                )
            user_exit_ports[ch.exit_port] = ch.name
        if ch.relay_port:
            if ch.relay_port in user_relay_ports:
                raise ValueError(
                    f"Channels {user_relay_ports[ch.relay_port]!r} and {ch.name!r} "
                    f"both claim relay_port {ch.relay_port} — each channel must "
                    "land on a different port on the relay panel."
                )
            user_relay_ports[ch.relay_port] = ch.name

    # Apply user-supplied ports first (so the auto-pick respects them
    # as "already chosen"), then fill gaps.
    auto_exit = set(user_exit_ports.keys())
    auto_relay = set(user_relay_ports.keys())
    for ch in draft.channels:
        if ch.exit_port == 0:
            ch.exit_port = _pick_port(auto_exit, exit_used, 10000, 19999)
        elif ch.exit_port in exit_used:
            why = "reserved by panel HTTPS (Caddy / ACME)" \
                if ch.exit_port in (80, 443) and exit_xs.mode == "xui-pro" \
                else "already in use on exit panel"
            raise ValueError(
                f"Channel {ch.name!r}: exit_port {ch.exit_port} — {why}"
            )
        if ch.relay_port == 0:
            ch.relay_port = _pick_port(auto_relay, relay_used, 20000, 29999)
        elif ch.relay_port in relay_used:
            why = "reserved by panel HTTPS (Caddy / ACME)" \
                if ch.relay_port in (80, 443) and relay_xs.mode == "xui-pro" \
                else "already in use on relay panel"
            raise ValueError(
                f"Channel {ch.name!r}: relay_port {ch.relay_port} — {why}"
            )

    # Step 3 — DB rows. Commit so we have a chain_id to use in tags
    # BEFORE any panel mutation; rollback on failure drops these
    # via session.delete.
    now = datetime.now(timezone.utc)
    chain = ProxyChain(
        name=draft.name,
        exit_xui_server_id=exit_xs.id,
        relay_xui_server_id=relay_xs.id,
        exit_sni=draft.exit_sni,
        status="pending",
        created_at=now,
        updated_at=now,
    )
    session.add(chain)
    await session.flush()  # populates chain.id without commit

    channel_rows: List[ChainChannel] = []
    for order, draft_ch in enumerate(draft.channels):
        row = ChainChannel(
            chain_id=chain.id,
            name=draft_ch.name,
            order=order,
            exit_port=draft_ch.exit_port,
            relay_port=draft_ch.relay_port,
            exit_xhttp_path=draft_ch.exit_xhttp_path or f"/api/v1/{draft_ch.name}",
            client_sni=draft_ch.client_sni,
            relay_inbound_remark=draft_ch.relay_remark or f"VPN-{draft_ch.name.upper()}",
            exit_inbound_remark=draft_ch.exit_remark or f"{draft_ch.name.upper()}-Exit",
            created_at=now,
        )
        session.add(row)
        channel_rows.append(row)
    await session.flush()  # populate row.id for each channel
    await session.commit()
    # commit() above expires every attached ORM instance. The loop in
    # step 4 below reads `ch.name` / `chain.id` / etc., which would
    # otherwise trigger SQLAlchemy's sync lazy-load callback inside
    # the async session — `MissingGreenlet: can't call await_only()`.
    # Refresh them eagerly to repopulate the attribute cache.
    await session.refresh(chain)
    for row in channel_rows:
        await session.refresh(row)

    # Step 4 — panel-side create. Track every (panel, remote_id)
    # pair we successfully add so rollback can undo them.
    created_exit: List[int] = []   # remote_ids on exit panel
    created_relay: List[int] = []  # remote_ids on relay panel

    try:
        async with XuiClient(
            base_url=exit_url, api_token=exit_token, verify_tls=False,
        ) as exit_client, XuiClient(
            base_url=relay_url, api_token=relay_token, verify_tls=False,
            panel_user=relay_user, panel_pass=relay_pass,
        ) as relay_client:

            for ch in channel_rows:
                draft_ch = next(d for d in draft.channels if d.name == ch.name)

                # Per-channel crypto material.
                bootstrap_uuid = await exit_client.get_new_uuid()
                exit_pvk, exit_pbk = await exit_client.get_new_x25519_cert()
                relay_pvk, relay_pbk = await relay_client.get_new_x25519_cert()
                exit_sid = secrets.token_hex(4)
                relay_sid = secrets.token_hex(4)
                bootstrap_email = f"chain-{chain.id}-{ch.name}-boot"

                # 4b. Exit inbound.
                exit_payload = _build_exit_inbound_payload(
                    chain_id=chain.id, channel=draft_ch,
                    bootstrap_uuid=bootstrap_uuid,
                    exit_sni=draft.exit_sni,
                    private_key=exit_pvk, public_key=exit_pbk,
                    short_id=exit_sid,
                    bootstrap_email=bootstrap_email,
                )
                exit_created = await exit_client.add_inbound(
                    _wrap_settings_json(exit_payload),
                )
                exit_id = int(exit_created.get("id") or 0)
                if not exit_id:
                    raise XuiAPIError(
                        "exit add_inbound returned no id",
                        kind="format",
                    )
                created_exit.append(exit_id)

                # 4c. Relay inbound.
                relay_payload = _build_relay_inbound_payload(
                    chain_id=chain.id, channel=draft_ch,
                    bootstrap_uuid=bootstrap_uuid,
                    private_key=relay_pvk, public_key=relay_pbk,
                    short_id=relay_sid,
                    bootstrap_email=bootstrap_email,
                )
                relay_created = await relay_client.add_inbound(
                    _wrap_settings_json(relay_payload),
                )
                relay_id = int(relay_created.get("id") or 0)
                if not relay_id:
                    raise XuiAPIError(
                        "relay add_inbound returned no id",
                        kind="format",
                    )
                created_relay.append(relay_id)

                # 4d. DB row updates — captured here so step 5 (config
                # build) reads them.
                ch.exit_inbound_remote_id = exit_id
                ch.relay_inbound_remote_id = relay_id
                ch.exit_uuid = bootstrap_uuid
                ch.exit_pbk = exit_pbk
                ch.exit_pvk = exit_pvk
                ch.exit_sid = exit_sid
                ch.relay_pbk = relay_pbk
                ch.relay_pvk = relay_pvk
                ch.relay_sid = relay_sid
                session.add(ch)
            await session.commit()
            # Same expire-on-commit gotcha as above — step 5 reads
            # chain.id, ch.exit_port, ch.relay_port, ch.exit_uuid, etc.
            await session.refresh(chain)
            for row in channel_rows:
                await session.refresh(row)

            # Step 4e — open the chain inbound ports in UFW. Without
            # this, SYNs from clients (relay) and from the relay's
            # chain outbound (exit) get silently dropped by the
            # default-deny ufw policy on a fresh VPS.
            exit_ports_open = [ch.exit_port for ch in channel_rows]
            relay_ports_open = [ch.relay_port for ch in channel_rows]
            await _ufw_chain_ports(exit_srv, exit_ports_open, action="allow")
            await _ufw_chain_ports(relay_srv, relay_ports_open, action="allow")

            # Step 5 — push xrayTemplateConfig to the relay. We
            # rebuild a COMBINED template covering every chain bound
            # to this relay (including the one we just inserted into
            # the DB at step 3) — the panel stores one template per
            # panel, so a single-chain push would wipe routes for any
            # other chains sharing the same relay.
            template = await build_combined_relay_template(
                session=session,
                relay_xui_server_id=chain.relay_xui_server_id,
            )
            await _push_xray_template(
                relay_client=relay_client, template=template,
            )

            # Step 6 — restart Xray on the relay.
            await _restart_xray(relay_client)

    except Exception as exc:  # noqa: BLE001
        # Rollback panel-side state. Best-effort: a failed delete
        # here just means the operator has stranded inbounds they
        # can clean up via the panel UI — we'd rather raise the
        # original create error than mask it with a rollback error.
        logger.warning(
            "Chain create failed for chain id=%s, rolling back %s exit + %s relay inbounds: %s",
            chain.id, len(created_exit), len(created_relay), exc,
        )
        await _rollback_inbounds(
            exit_url=exit_url, exit_token=exit_token,
            relay_url=relay_url, relay_token=relay_token,
            exit_ids=created_exit, relay_ids=created_relay,
        )
        chain.status = "failed"
        chain.last_error = f"{type(exc).__name__}: {str(exc)[:900]}"
        chain.updated_at = datetime.now(timezone.utc)
        session.add(chain)
        await session.commit()
        raise

    # Step 7 — finalise.
    chain.status = "deployed"
    chain.last_error = None
    chain.last_synced_at = datetime.now(timezone.utc)
    chain.updated_at = chain.last_synced_at
    session.add(chain)
    await session.commit()
    await session.refresh(chain)
    return chain


async def _rollback_inbounds(
    *,
    exit_url: str, exit_token: str,
    relay_url: str, relay_token: str,
    exit_ids: List[int], relay_ids: List[int],
) -> None:
    """Best-effort `del_inbound` for every (panel, id) we created
    before the failure. Errors here are logged but not raised — the
    caller's exception is the actionable one."""
    if exit_ids:
        try:
            async with XuiClient(
                base_url=exit_url, api_token=exit_token, verify_tls=False,
            ) as c:
                for rid in exit_ids:
                    try:
                        await c.del_inbound(rid)
                    except Exception as e:  # noqa: BLE001
                        logger.warning(
                            "rollback: del_inbound %s on exit panel failed: %s",
                            rid, e,
                        )
        except Exception as e:  # noqa: BLE001
            logger.warning("rollback: exit panel unreachable for cleanup: %s", e)
    if relay_ids:
        try:
            async with XuiClient(
                base_url=relay_url, api_token=relay_token, verify_tls=False,
            ) as c:
                for rid in relay_ids:
                    try:
                        await c.del_inbound(rid)
                    except Exception as e:  # noqa: BLE001
                        logger.warning(
                            "rollback: del_inbound %s on relay panel failed: %s",
                            rid, e,
                        )
        except Exception as e:  # noqa: BLE001
            logger.warning("rollback: relay panel unreachable for cleanup: %s", e)


# ── Delete ──────────────────────────────────────────────────────────────────


async def orchestrate_delete_channel(
    *,
    chain: ProxyChain,
    channel: ChainChannel,
    session: AsyncSession,
) -> bool:
    """Remove a single channel from an existing chain.

    Pipeline (mirror of `orchestrate_delete`'s per-channel work, scoped
    to one channel + leaving the chain row alive if other channels
    remain):
      1. Delete the channel's exit-side inbound on the exit panel.
      2. Delete the channel's relay-side inbound on the relay panel.
      3. Close exit_port + relay_port in UFW on each VPS.
      4. Rebuild the combined relay template covering the remaining
         channels + restart relay Xray.
      5. Cascade-delete every `Node` row exported from this channel's
         ChainClientChannel rows. Without this they'd survive as
         orphans pointing at a UUID that no longer authenticates.
      6. Drop the ChainChannel DB row — cascades ChainClientChannel
         pairs via FK ON DELETE CASCADE.

    If this was the *last* channel of the chain, the orchestrator
    skips the relay-template repush (nothing left to route) and
    asks the caller to tear down the chain entirely. Returns True
    when the chain has remaining channels (UI keeps it visible),
    False when the caller should drop the ProxyChain row too.
    """
    _no_expire_on_commit(session)

    exit_xs = await session.get(XuiServer, chain.exit_xui_server_id)
    relay_xs = await session.get(XuiServer, chain.relay_xui_server_id)
    exit_srv = await session.get(Server, exit_xs.server_id) if exit_xs else None
    relay_srv = await session.get(Server, relay_xs.server_id) if relay_xs else None

    # Count siblings UP FRONT so the return value + the relay-template
    # branching agree regardless of which inner blocks executed.
    from sqlmodel import select as _select
    siblings_q = _select(ChainChannel).where(
        ChainChannel.chain_id == chain.id,
    ).where(ChainChannel.id != channel.id)
    siblings = list((await session.exec(siblings_q)).all())
    has_siblings = bool(siblings)

    # 1. Exit-side inbound.
    if exit_xs and exit_srv and channel.exit_inbound_remote_id:
        try:
            async with XuiClient(
                base_url=_api_base_url(exit_xs, exit_srv),
                api_token=exit_xs.api_token, verify_tls=False,
            ) as c:
                try:
                    await c.del_inbound(channel.exit_inbound_remote_id)
                except Exception as e:  # noqa: BLE001
                    logger.warning(
                        "delete_channel: exit inbound %s removal failed: %s",
                        channel.exit_inbound_remote_id, e,
                    )
        except Exception as e:  # noqa: BLE001
            logger.warning("delete_channel: exit panel unreachable: %s", e)

    # 2+4. Relay-side inbound + template re-push.
    if relay_xs and relay_srv and channel.relay_inbound_remote_id:
        try:
            async with XuiClient(
                base_url=_api_base_url(relay_xs, relay_srv),
                api_token=relay_xs.api_token, verify_tls=False,
                panel_user=relay_xs.panel_user, panel_pass=relay_xs.panel_pass,
            ) as c:
                try:
                    await c.del_inbound(channel.relay_inbound_remote_id)
                except Exception as e:  # noqa: BLE001
                    logger.warning(
                        "delete_channel: relay inbound %s removal failed: %s",
                        channel.relay_inbound_remote_id, e,
                    )
                if has_siblings:
                    # Other channels still ride this relay — rebuild
                    # the combined template *excluding* this channel.
                    # `build_combined_relay_template` reads from DB,
                    # so we delete the DB row FIRST then rebuild.
                    await session.delete(channel)
                    await session.flush()
                    template = await build_combined_relay_template(
                        session=session,
                        relay_xui_server_id=chain.relay_xui_server_id,
                    )
                    try:
                        await _push_xray_template(
                            relay_client=c, template=template,
                        )
                        await _restart_xray(c)
                    except Exception as e:  # noqa: BLE001
                        logger.warning(
                            "delete_channel: relay template repush failed: %s", e,
                        )
                else:
                    # Last channel — clear the panel template entirely
                    # so the panel's auto-routing kicks back in. We
                    # also clear via SSH because pushing an empty
                    # template doesn't reset xray's running config
                    # (the bare-panel gotcha we hit in beta.7).
                    await session.delete(channel)
                    await session.flush()
                    try:
                        await _clear_xray_template_via_ssh(relay_srv)
                    except Exception as e:  # noqa: BLE001
                        logger.warning(
                            "delete_channel: relay template clear failed: %s", e,
                        )
        except Exception as e:  # noqa: BLE001
            logger.warning("delete_channel: relay panel unreachable: %s", e)
    else:
        # No relay panel reachable to issue del_inbound — still drop
        # the DB row so PiTun's view stays consistent.
        await session.delete(channel)
        await session.flush()

    # 3. UFW close (best-effort, both sides).
    if exit_srv and channel.exit_port:
        await _ufw_chain_ports(
            exit_srv, [channel.exit_port], action="delete-allow",
        )
    if relay_srv and channel.relay_port:
        await _ufw_chain_ports(
            relay_srv, [channel.relay_port], action="delete-allow",
        )

    # 5. Cascade-clean Node rows that were exported from this
    # channel's ChainClientChannel pairs. The FK ChainClientChannel
    # → Node is ON DELETE SET NULL, so the link rows vanish with
    # the channel cascade but the Nodes survive — match them by
    # name suffix (`-<channel.name>`, the convention from
    # `export_chain_client_nodes`) and address (relay host) so we
    # never collateral-delete an unrelated Node.
    from app.models import Node
    suffix = f"-{channel.name}"
    orphan_nodes = list((await session.exec(
        _select(Node).where(Node.name.like(f"%{suffix}"))
    )).all())
    for n in orphan_nodes:
        if relay_srv and n.address == relay_srv.host:
            await session.delete(n)

    await session.commit()
    return has_siblings


async def orchestrate_delete(
    *,
    chain: ProxyChain,
    channels: List[ChainChannel],
    session: AsyncSession,
) -> None:
    """Tear down a chain on both panels + drop the DB rows.

    Best-effort: deletes that fail on the panel side are logged but
    don't block the DB cleanup — the row matters less than leaving
    PiTun with phantom chain references the UI can't act on.
    Re-pushing an empty xrayTemplateConfig (no chain outbounds) on
    the relay is **not** strictly necessary — xray will silently
    ignore routing rules pointing at outbounds that no longer exist
    after the inbounds disappear — but doing it anyway gives us a
    clean slate for the next chain on the same relay. So we do.
    """
    _no_expire_on_commit(session)
    exit_xs = await session.get(XuiServer, chain.exit_xui_server_id)
    relay_xs = await session.get(XuiServer, chain.relay_xui_server_id)
    exit_srv = await session.get(Server, exit_xs.server_id) if exit_xs else None
    relay_srv = await session.get(Server, relay_xs.server_id) if relay_xs else None

    if exit_xs and exit_srv:
        try:
            async with XuiClient(
                base_url=_api_base_url(exit_xs, exit_srv),
                api_token=exit_xs.api_token, verify_tls=False,
            ) as c:
                for ch in channels:
                    if ch.exit_inbound_remote_id:
                        try:
                            await c.del_inbound(ch.exit_inbound_remote_id)
                        except Exception as e:  # noqa: BLE001
                            logger.warning(
                                "delete: exit inbound %s removal failed: %s",
                                ch.exit_inbound_remote_id, e,
                            )
        except Exception as e:  # noqa: BLE001
            logger.warning("delete: exit panel unreachable: %s", e)

    if relay_xs and relay_srv:
        try:
            async with XuiClient(
                base_url=_api_base_url(relay_xs, relay_srv),
                api_token=relay_xs.api_token, verify_tls=False,
                panel_user=relay_xs.panel_user, panel_pass=relay_xs.panel_pass,
            ) as c:
                for ch in channels:
                    if ch.relay_inbound_remote_id:
                        try:
                            await c.del_inbound(ch.relay_inbound_remote_id)
                        except Exception as e:  # noqa: BLE001
                            logger.warning(
                                "delete: relay inbound %s removal failed: %s",
                                ch.relay_inbound_remote_id, e,
                            )
                # Two paths depending on whether this relay still
                # carries OTHER chains:
                #   * yes → rebuild a COMBINED template covering the
                #           remaining chains. Pushing an empty
                #           template would wipe their routes (the
                #           beta.7 footgun: deleting chain A killed
                #           chain B because both rode this relay).
                #   * no  → DELETE the `xrayTemplateConfig` key
                #           entirely so the panel falls back to its
                #           auto-generated routing for the standalone
                #           inbounds (regular vless / trojan / socks
                #           added through the X-ui page). Just
                #           pushing `xraySetting=""` doesn't reset
                #           the running config — only a hard sqlite
                #           DELETE + `x-ui restart` does, so we run
                #           that over SSH.
                try:
                    from sqlmodel import select as _select
                    others_q = _select(ProxyChain).where(
                        ProxyChain.relay_xui_server_id == chain.relay_xui_server_id,
                    ).where(ProxyChain.id != chain.id)
                    others = list((await session.exec(others_q)).all())
                    if others:
                        template = await build_combined_relay_template(
                            session=session,
                            relay_xui_server_id=chain.relay_xui_server_id,
                            exclude_chain_id=chain.id,
                        )
                        await _push_xray_template(
                            relay_client=c, template=template,
                        )
                        await _restart_xray(c)
                    else:
                        # Last chain on this relay — restore panel's
                        # auto-routing.
                        await _clear_xray_template_via_ssh(relay_srv)
                except Exception as e:  # noqa: BLE001
                    logger.warning(
                        "delete: relay template cleanup failed: %s", e,
                    )
        except Exception as e:  # noqa: BLE001
            logger.warning("delete: relay panel unreachable: %s", e)

    # Close the chain ports in UFW on both VPSes. Mirror of the
    # `_ufw_chain_ports(..., action="allow")` calls in
    # orchestrate_create. Best-effort.
    if exit_srv:
        await _ufw_chain_ports(
            exit_srv,
            [ch.exit_port for ch in channels if ch.exit_port],
            action="delete-allow",
        )
    if relay_srv:
        await _ufw_chain_ports(
            relay_srv,
            [ch.relay_port for ch in channels if ch.relay_port],
            action="delete-allow",
        )

    # DB cleanup — channels + clients + client-channels cascade from
    # the chain row via ON DELETE CASCADE in the migration.
    await session.delete(chain)
    await session.commit()


# ── Client lifecycle ────────────────────────────────────────────────────────


async def orchestrate_add_client(
    *,
    chain: ProxyChain,
    channels: List[ChainChannel],
    label: Optional[str],
    session: AsyncSession,
) -> ChainClient:
    """Add a client to every relay-side inbound at once.

    The user gets back a `ChainClient` row with N
    `ChainClientChannel` children — one panel-side client UUID per
    channel. Each can be independently exported to a Node later.

    Rollback: if addClient on channel K of N fails, we delClient on
    channels 0..K-1 to keep the user/channel cardinality in lock-step
    (otherwise /sync would report N-1 hand-added clients next time).
    """
    _no_expire_on_commit(session)
    relay_xs = await session.get(XuiServer, chain.relay_xui_server_id)
    if relay_xs is None:
        raise RuntimeError(f"relay panel id={chain.relay_xui_server_id} missing")
    relay_srv = await session.get(Server, relay_xs.server_id)
    if relay_srv is None:
        raise RuntimeError(f"Server id={relay_xs.server_id} missing")

    effective_label = label or f"pi-{secrets.token_hex(4)}"

    chain_client = ChainClient(
        chain_id=chain.id,
        label=effective_label,
    )
    session.add(chain_client)
    await session.flush()

    relay_url = _api_base_url(relay_xs, relay_srv)
    added: List[tuple[int, str]] = []   # (inbound_remote_id, uuid) for rollback

    try:
        async with XuiClient(
            base_url=relay_url, api_token=relay_xs.api_token, verify_tls=False,
        ) as c:
            for ch in channels:
                uuid = await c.get_new_uuid()
                # v3.1.0: email is globally unique on ClientRecord
                # (uniqueIndex). Same `effective_label` across N
                # channels would collide on the 2nd add_client call.
                # Suffix with the channel's stable name so each
                # panel-side client is distinct ("alice-vk", "alice-mx",
                # ...). The UI groups them logically by prefix, and
                # PiTun's ChainClient → ChainClientChannel mapping
                # still owns the per-channel UUID for Node export.
                client_obj = {
                    "id": uuid,
                    "flow": "xtls-rprx-vision",
                    "email": f"{effective_label}-{ch.name}",
                    "limitIp": 0, "totalGB": 0, "expiryTime": 0,
                    "enable": True, "tgId": "", "subId": "",
                }
                await c.add_client(ch.relay_inbound_remote_id, client_obj)
                added.append((ch.relay_inbound_remote_id, uuid))

                cc = ChainClientChannel(
                    chain_client_id=chain_client.id,
                    channel_id=ch.id,
                    client_uuid=uuid,
                )
                session.add(cc)
            # x-ui-pro persists the client to the panel DB but doesn't
            # automatically reload Xray's running config (the generated
            # /usr/local/x-ui/bin/config.json still has only the prior
            # clients). Without this restart, the new UUID returns a
            # silent Reality drop → "Offline" Node + zero-byte speed
            # tests. Bounce Xray to pick up the inbound update.
            await c.restart_xray()
    except Exception:
        # Rollback panel-side adds (best-effort).
        if added:
            try:
                async with XuiClient(
                    base_url=relay_url, api_token=relay_xs.api_token,
                    verify_tls=False,
                ) as c2:
                    for inbound_id, uuid in added:
                        try:
                            await c2.del_client(inbound_id, uuid)
                        except Exception as e:  # noqa: BLE001
                            logger.warning(
                                "rollback: del_client (%s,%s) failed: %s",
                                inbound_id, uuid, e,
                            )
            except Exception as e:  # noqa: BLE001
                logger.warning(
                    "rollback: relay panel unreachable during client cleanup: %s",
                    e,
                )
        # Drop the (partial) DB rows before re-raising.
        await session.rollback()
        raise

    await session.commit()
    await session.refresh(chain_client)
    return chain_client


async def orchestrate_delete_client(
    *,
    chain: ProxyChain,
    chain_client: ChainClient,
    pairs: List[ChainClientChannel],
    channels_by_id: Dict[int, ChainChannel],
    session: AsyncSession,
) -> None:
    """Remove every panel-side client this ChainClient maps to, drop
    any Nodes that were exported from its channels, then drop the DB
    row (which cascades the ClientChannel pairs).

    Cascade rationale: a ChainClientChannel may have an
    `exported_node_id` pointing at a `Node` row that the user
    created via "Export to Node". Without this cleanup, removing
    the chain client leaves orphan Node rows whose UUID no longer
    authenticates against the panel (panel-side client is gone),
    cluttering the Nodes page and making routing rules referencing
    them fail silently. Mirror of the cascade in
    `xui.py::delete_client` (line 1607+) for regular x-ui clients.
    """
    from app.models import Node
    _no_expire_on_commit(session)

    # Step 1: collect Nodes to delete BEFORE we drop ChainClientChannel
    # rows (FK cascade would lose the linkage otherwise).
    nodes_to_delete: list[Node] = []
    for pair in pairs:
        if pair.exported_node_id is None:
            continue
        node = await session.get(Node, pair.exported_node_id)
        if node is not None:
            nodes_to_delete.append(node)

    relay_xs = await session.get(XuiServer, chain.relay_xui_server_id)
    relay_srv = (
        await session.get(Server, relay_xs.server_id) if relay_xs else None
    )

    # Step 2: panel-side delete (best-effort — proceed to DB cleanup
    # even if the relay is unreachable).
    if relay_xs is not None and relay_srv is not None:
        try:
            async with XuiClient(
                base_url=_api_base_url(relay_xs, relay_srv),
                api_token=relay_xs.api_token, verify_tls=False,
            ) as c:
                for pair in pairs:
                    ch = channels_by_id.get(pair.channel_id)
                    if ch is None:
                        continue
                    try:
                        await c.del_client(
                            ch.relay_inbound_remote_id, pair.client_uuid,
                        )
                    except Exception as e:  # noqa: BLE001
                        logger.warning(
                            "delete client: panel del_client (%s,%s) failed: %s",
                            ch.relay_inbound_remote_id, pair.client_uuid, e,
                        )
                # Mirror orchestrate_add_client: x-ui-pro persists the
                # delete to the panel DB but doesn't reload Xray, so the
                # removed UUID would keep working until the next restart.
                try:
                    await c.restart_xray()
                except Exception as e:  # noqa: BLE001
                    logger.warning("delete client: restart_xray failed: %s", e)
        except Exception as e:  # noqa: BLE001
            logger.warning("delete client: relay panel unreachable: %s", e)

    # Step 3: cascade-delete exported Nodes + ChainClientChannel pairs
    # + the ChainClient row itself. The FK `ChainClientChannel ->
    # ChainClient` has no `ondelete="CASCADE"` declaration in the
    # migration, and SQLAlchemy doesn't infer ORM-level cascade from a
    # plain Field-with-foreign_key — so dropping the parent leaves the
    # child rows orphaned in the DB unless we delete them here too.
    # (Verified by `TestOrchestrateDeleteClient` regression test.)
    for node in nodes_to_delete:
        logger.info(
            "delete chain client %d (%s): also dropping exported Node %d (%s)",
            chain_client.id, chain_client.label, node.id, node.name,
        )
        await session.delete(node)
    for pair in pairs:
        await session.delete(pair)
    await session.delete(chain_client)
    await session.commit()
